global
        log 127.0.0.1   local0
        log 127.0.0.1   local1 notice
        maxconn 4096
        chroot /var/lib/haproxy
        user haproxy
        group haproxy
        daemon
        #debug
        #quiet

defaults
        log     global
        mode    http
        option  httplog
        option  dontlognull
        option redispatch
        retries 3
        maxconn 2000
        contimeout      5000
        clitimeout      50000
        srvtimeout      50000

# Comment to disable web stats or see full doc to
# secure it
listen stats :5000
    mode http
    stats enable
    stats hide-version
    stats realm Haproxy\ Statistics
    stats uri /
    stats auth Username:Password # CHANGE THIS!

listen oml2server :3003
        mode tcp
        option tcplog
        balance leastconn

        server oml2server1 192.0.2.1:3003 check
        server oml2server2 192.0.2.2:3003 check
        server oml2server3 192.0.2.3:3003 check
